language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install

script: composer travis

after_success:
 - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar -O coveralls.phar
 - php coveralls.phar -v
