language: php

sudo: false

php:
  - 8.0

before_script:
  - composer self-update
  - composer install
  - test -f $HOME/.composer/cache/phpstan.phar || wget https://github.com/phpstan/phpstan/releases/download/0.12.94/phpstan.phar -O $HOME/.composer/cache/phpstan.phar

script:
  - composer travis
  - php $HOME/.composer/cache/phpstan.phar analyze -l 7 ./src

after_success:
 - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.3/php-coveralls.phar -O coveralls.phar
 - php coveralls.phar -v
